 interface Contratos{
  servico: string;
  numero:string;
  fornecedor:string;
  vencimento:string;
  periodo:string;
  dacc:boolean;
}
export interface Generico {
  contratos: any[];
  id?: string;
  nome: string;
  conta: string;
  agencia: string;
  banco: string;
  chavepix: string;
  cnpj: string;
  conselhofiscal1: string;
  conselhofiscal2: string;
  conselhofiscal3: string;
  cpfconselhofiscal1: string;
  cpfconselhofiscal2: string;
  cpfconselhofiscal3: string;
  sindico: string;
  cpfsindico: string;
  subsindico: string;
  cpfsubsindico: string;
  email: string;
  endereco: string;
  operacao: string;
  pix: string;
  telefone: string;
  titular: string;
  unidade: string;
  locatario: string;
  condominio: string;
  observacao: string;
  servicosPrestados: string;
  cpf: string;
  admissao: string;
  cargo: string;
  apelido: string;
  proprietariocpf: string;
  locatariocpf: string;
  rg: string;
  pis: string;
  nascimento: string;
  filiacaopai: string;
  filiacaomae: string;
}
